services:
  postgres:
    image: postgres:15
    container_name: postgres-db-flowbank
    restart: always
    environment:
      POSTGRES_DB: flowbank_db
      POSTGRES_USER: flowbank
      POSTGRES_PASSWORD: flowbank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - flowbank

  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  flowbank:
    build: .
    container_name: flowbank
    env_file:
      - .env
    ports:
      - "${SPRING_SERVER_PORT}:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_HTTP_API_KEY: ${APP_HTTP_API_KEY}
      APP_HTTP_API_KEY_HEADER: ${APP_HTTP_API_KEY_HEADER}
      SPRING_SERVER_PORT: ${SPRING_SERVER_PORT}
    restart: unless-stopped
volumes:
  postgres_data:
  grafana_data:

