global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flowbank"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["flowbank:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
